apiVersion: v1
kind: ConfigMap
metadata:
  name: rosettacloud-backend-config
  namespace: openedx
data:
  LAB_IMAGE_PULL_SECRET: "True"
  MOMENTO_API_KEY: "ey"
  AWS_ACCESS_KEY_ID: "AK"
  AWS_SECRET_ACCESS_KEY: "ol3xo"
  AWS_REGION: "us-east-1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosettacloud-backend
  namespace: openedx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rosettacloud-backend
  template:
    metadata:
      labels:
        app: rosettacloud-backend
    spec:
      containers:
        - name: rosettacloud-backend
          image: 339712964409.dkr.ecr.me-central-1.amazonaws.com/rosettacloud-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: LAB_IMAGE_PULL_SECRET
              valueFrom:
                configMapKeyRef:
                  name: rosettacloud-backend-config
                  key: LAB_IMAGE_PULL_SECRET
            - name: MOMENTO_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: rosettacloud-backend-config
                  key: MOMENTO_API_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: rosettacloud-backend-config
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: rosettacloud-backend-config
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: rosettacloud-backend-config
                  key: AWS_REGION
      imagePullSecrets:
        - name: ecr-creds

---
apiVersion: v1
kind: Service
metadata:
  name: rosettacloud-backend-service
  namespace: openedx
spec:
  selector:
    app: rosettacloud-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30085
